@endpoint=http://localhost:7200/repositories/staging

### Update staging repository
PUT {{endpoint}}
Content-Type: text/turtle

@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix rep: <http://www.openrdf.org/config/repository#>.
@prefix sr: <http://www.openrdf.org/config/repository/sail#>.
@prefix sail: <http://www.openrdf.org/config/sail#>.
@prefix graphdb: <http://www.ontotext.com/config/graphdb#>.

[] a rep:Repository ;
    rep:repositoryID "staging" ;
    rep:repositoryImpl [
        rep:repositoryType "graphdb:SailRepository" ;
        sr:sailImpl [
            sail:sailType "graphdb:Sail" ;

            graphdb:read-only "false" ;

            # Inference and Validation
            graphdb:ruleset "owl-max-optimized" ;
            graphdb:disable-sameAs "false" ;
            graphdb:check-for-inconsistencies "false" ;

            # Indexing
            graphdb:entity-id-size "32" ;
            graphdb:enable-context-index "false" ;
            graphdb:enablePredicateList "true" ;
            graphdb:enable-fts-index "false" ;
            graphdb:fts-indexes ("default" "iri") ;
            graphdb:fts-string-literals-index "default" ;
            graphdb:fts-iris-index "none" ;

            # Queries and Updates
            graphdb:query-timeout "0" ;
            graphdb:throw-QueryEvaluationException-on-timeout "false" ;
            graphdb:query-limit-results "0" ;

            # Settable in the file but otherwise hidden in the UI and in the RDF4J console
            graphdb:base-URL "http://example.org/owlim#" ;
            graphdb:defaultNS "" ;
            graphdb:imports "" ;
            graphdb:repository-type "file-repository" ;
            graphdb:storage-folder "storage" ;
            graphdb:entity-index-size "70000000" ;
            graphdb:in-memory-literal-properties "false" ;
            graphdb:enable-literal-index "false" ;
        ]
    ].

### Applying ontology
POST {{endpoint}}/statements
Content-Type: application/sparql-update
Accept: text/turtle

prefix :<http://id.example.com/schema/>
prefix this:<http://id.example.com/>
prefix rdfs:<http://www.w3.org/2000/01/rdf-schema#>
prefix owl:<http://www.w3.org/2002/07/owl#>
prefix xsd:<http://www.w3.org/2001/XMLSchema#>
prefix rico:<https://www.ica.org/standards/RiC/ontology#>

insert data {
  _:b1 <http://www.ontotext.com/owlim/system#schemaTransaction> _:b2.

  <Paste content of the Ontology.ttl excluding prefixes>
}

### Modifying ontology
POST {{endpoint}}/statements
Content-Type: application/sparql-update
Accept: text/turtle

prefix :<http://id.example.com/schema/>
prefix this:<http://id.example.com/>
prefix rdfs:<http://www.w3.org/2000/01/rdf-schema#>
prefix owl:<http://www.w3.org/2002/07/owl#>
prefix xsd:<http://www.w3.org/2001/XMLSchema#>
prefix rico:<https://www.ica.org/standards/RiC/ontology#>

delete {
  <List statements to delete>
}
insert {
  _:b1 <http://www.ontotext.com/owlim/system#schemaTransaction> _:b2.
}
where {}

### Index compacting
POST {{endpoint}}/statements
Content-Type: application/sparql-update
Accept: text/turtle

insert data { [] <http://www.ontotext.com/compactIndexes> [] }

### SameAs check
POST {{endpoint}}
Content-Type: application/sparql-query
Accept: text/turtle

prefix owl: <http://www.w3.org/2002/07/owl#>

construct {
    ?s owl:sameAs ?s2.
} where {
    ?s owl:sameAs ?s2.
}

### Description diff check
POST {{endpoint}}
Content-Type: application/sparql-query
Accept: application/sparql-results+json

prefix ex: <http://id.example.com/schema/>
prefix dcterms: <http://purl.org/dc/terms/description>

select * where {
    ?asset ex:assetHasVariation ?variation;
		  ex:assetDescription ?assetDescription.
    ?variation <http://purl.org/dc/terms/description> ?variationDescription.
    filter (?assetDescription!=?variationDescription)
}

### Access conditions count
POST {{endpoint}}
Content-Type: application/sparql-query
Accept: application/sparql-results+json

prefix ex: <http://id.example.com/schema/>

select (count(?s) as ?x) where {
    ?s ex:accessConditionCode ?code.
}

### Access conditions
POST {{endpoint}}
Content-Type: application/sparql-query
Accept: text/turtle

prefix ex: <http://id.example.com/schema/>

construct {
    ?s ex:accessConditionCode ?code;
      ex:accessConditionName ?accessConditionName.
} where {
    ?s ex:accessConditionCode ?code;
      ex:accessConditionName ?accessConditionName.
}

### Legislation count
POST {{endpoint}}
Content-Type: application/sparql-query

prefix ex: <http://id.example.com/schema/>

select (count(?s) as ?x) where {
    ?s ex:legislationHasUkLegislation ?legislationHasUkLegislation.
}

### Legislations
POST {{endpoint}}
Content-Type: application/sparql-query
Accept: text/turtle

prefix ex: <http://id.example.com/schema/>

construct {
    ?s ex:legislationHasUkLegislation ?legislationHasUkLegislation;
      ex:legislationSectionReference ?legislationSectionReference.
} where {
    ?s ex:legislationHasUkLegislation ?legislationHasUkLegislation.
    optional { ?s ex:legislationSectionReference ?legislationSectionReference }
}

### Ground for retention count
POST {{endpoint}}
Content-Type: application/sparql-query

prefix ex: <http://id.example.com/schema/>

select (count(?s) as ?x) where {
    ?s ex:groundForRetentionCode ?groundForRetentionCode.
}

### Grounds for retention
POST {{endpoint}}
Content-Type: application/sparql-query
Accept: text/turtle

prefix ex: <http://id.example.com/schema/>

construct {
    ?s ex:groundForRetentionCode ?groundForRetentionCode;
      ex:groundForRetentionDescription ?groundForRetentionDescription.
} where {
    ?s ex:groundForRetentionCode ?groundForRetentionCode.
    optional { ?s ex:groundForRetentionDescription ?groundForRetentionDescription }
}

### Subsets count
POST {{endpoint}}
Content-Type: application/sparql-query

prefix ex: <http://id.example.com/schema/>

select (count(distinct ?subsetReference) as ?x) where {
    ?subset ex:subsetReference ?subsetReference.
}

### Subsets
POST {{endpoint}}
Content-Type: application/sparql-query

prefix ex: <http://id.example.com/schema/>

select ?subsetReference where {
    ?subset ex:subsetReference ?subsetReference.
} order by ?subsetReference

### Assets count
POST {{endpoint}}
Content-Type: application/sparql-query

prefix ex: <http://id.example.com/schema/>

select (count(?assetReference) as ?x) where {
    ?asset ex:assetReference ?assetReference.
}

### Variations count
POST {{endpoint}}
Content-Type: application/sparql-query

prefix ex: <http://id.example.com/schema/>

select (count(?variation) as ?x) where {
    ?variation ex:variationName ?variationName.
}

### Sensitivity reviews count
POST {{endpoint}}
Content-Type: application/sparql-query

prefix ex: <http://id.example.com/schema/>

select (count(?id) as ?x) where {
    ?sr ex:sensitivityReviewDriId ?id.
}