prefix ex: <http://example.com/schema/>
            
construct {
    ?subset ex:sensitivityReviewDriId ?sensitivityReviewDriId.
} where {
    bind(@id as ?sensitivityReviewDriId)
    ?subset ex:sensitivityReviewDriId ?sensitivityReviewDriId.
}