prefix ex: <http://id.example.com/schema/>

construct {
    ?s ex:groundForRetentionCode ?groundForRetentionCode;
        ex:groundForRetentionDescription ?groundForRetentionDescription.
} where {
    bind(@id as ?groundForRetentionCode)
    ?s ex:groundForRetentionCode ?groundForRetentionCode.
    optional { ?s ex:groundForRetentionDescription ?groundForRetentionDescription }
}