prefix ex: <http://id.example.com/schema/>

construct {
    ?variation ex:variationDriId ?variationDriId;
        ex:variationHasAsset ?asset;
        ex:variationName ?variationName.
} where {
    bind(@id as ?variationDriId)
    ?variation ex:variationDriId ?variationDriId;
        ex:variationHasAsset ?asset;
        ex:variationName ?variationName.
}