prefix ex: <http://id.example.com/schema/>

construct {
    ?asset ex:assetDriId ?assetDriId;
        ex:assetDriXml ?assetDriXml;
        ex:assetPastReference ?assetPastReference;
        ex:assetDescription ?assetDescription;
        ex:assetSummary ?assetSummary;
        ex:batchDriId ?batchDriId;
        ex:consignmentTdrId ?consignmentTdrId;
        ex:assetRelationDescription ?assetRelationDescription;
        ex:assetPhysicalDescription ?assetPhysicalDescription;
        ex:assetUsageRestrictionDescription ?assetUsageRestrictionDescription;
        ex:assetTag ?assetTag;
        ex:assetSourceInternalName ?assetSourceInternalName;
        ex:filmProductionCompanyName ?filmProductionCompanyName;
        ex:filmTitle ?filmTitle;
        ex:filmDuration ?filmDuration;
        ex:photographerDescription ?photographerDescription;
        ex:evidenceProviderName ?evidenceProviderName;
        ex:investigationName ?investigationName;
        ex:courtSessionDescription ?courtSessionDescription;
        ex:courtSessionDate ?courtSessionDate;
        ex:inquirySessionDescription ?inquirySessionDescription;
        ex:inquiryHearingDate ?inquiryHearingDate;
        ex:imageSequenceStart ?imageSequenceStart;
        ex:imageSequenceEnd ?imageSequenceEnd;
        ex:paperNumber ?paperNumber;
        ex:assetHasUkGovernmentWebArchive ?assetHasUkGovernmentWebArchive;
        ex:assetHasLanguage ?language;
        ex:assetHasLegalStatus ?legalStatus;
        ex:assetHasCopyright ?copyright;
        ex:assetHasAssociatedGeographicalPlace ?associatedGeographicalPlace;
        ex:assetHasRetention ?retention;
        ex:assetHasCreation ?creation;
        ex:assetHasOriginDateStart ?originDateStart;
        ex:assetHasOriginDateEnd ?originDateEnd;
        ex:assetHasOriginApproximateDateStart ?originApproximateDateStart;
        ex:assetHasOriginApproximateDateEnd ?originApproximateDateEnd;
        ex:courtAssetHasCourtCase ?courtCase;
        ex:inquiryAssetHasInquiryAppearance ?inquiryAppearance.
    ?retention ex:retentionHasFormalBody ?retentionHasFormalBody.
    ?creation ex:creationHasFormalBody ?creationHasFormalBody.
    ?originDateStart ex:year ?startYear;
        ex:month ?startMonth;
        ex:day ?startDay.
    ?originDateEnd ex:year ?endYear;
        ex:month ?endMonth;
        ex:day ?endDay.
    ?originApproximateDateStart ex:year ?approximateStartYear;
        ex:month ?approximateStartMonth;
        ex:day ?approximateStartDay.
    ?originApproximateDateEnd ex:year ?approximateEndYear;
        ex:month ?approximateEndMonth;
        ex:day ?approximateEndDay.
    ?courtCase ex:courtCaseName ?courtCaseName;
        ex:courtCaseSummaryJudgment ?courtCaseSummaryJudgment;
        ex:courtCaseSummaryReasonsForJudgment ?courtCaseSummaryReasonsForJudgment;
        ex:courtCaseHearingStartDate ?courtCaseHearingStartDate;
        ex:courtCaseHearingEndDate ?courtCaseHearingEndDate.
    ?inquiryAppearance ex:inquiryWitnessName ?inquiryWitnessName;
        ex:inquiryWitnessAppearanceDescription ?inquiryWitnessAppearanceDescription.
} where {
    bind(@id as ?assetDriId)
    ?asset ex:assetDriId ?assetDriId.
    optional { ?asset ex:assetDriXml ?assetDriXml }
    optional { ?asset ex:assetPastReference ?assetPastReference }
    optional { ?asset ex:assetDescription ?assetDescription }
    optional { ?asset ex:assetSummary ?assetSummary }
    optional { ?asset ex:batchDriId ?batchDriId }
    optional { ?asset ex:consignmentTdrId ?consignmentTdrId }
    optional { ?asset ex:assetRelationDescription ?assetRelationDescription }
    optional { ?asset ex:assetPhysicalDescription ?assetPhysicalDescription }
    optional { ?asset ex:assetUsageRestrictionDescription ?assetUsageRestrictionDescription }
    optional { ?asset ex:assetTag ?assetTag }
    optional { ?asset ex:assetSourceInternalName ?assetSourceInternalName }
    optional { ?asset ex:filmProductionCompanyName ?filmProductionCompanyName }
    optional { ?asset ex:filmTitle ?filmTitle }
    optional { ?asset ex:filmDuration ?filmDuration }
    optional { ?asset ex:photographerDescription ?photographerDescription }
    optional { ?asset ex:evidenceProviderName ?evidenceProviderName }
    optional { ?asset ex:investigationName ?investigationName }
    optional { ?asset ex:courtSessionDescription ?courtSessionDescription }
    optional { ?asset ex:courtSessionDate ?courtSessionDate }
    optional { ?asset ex:inquirySessionDescription ?inquirySessionDescription }
    optional { ?asset ex:inquiryHearingDate ?inquiryHearingDate }
    optional { ?asset ex:imageSequenceStart ?imageSequenceStart }
    optional { ?asset ex:imageSequenceEnd ?imageSequenceEnd }
    optional { ?asset ex:paperNumber ?paperNumber }
    optional { ?asset ex:assetHasUkGovernmentWebArchive ?assetHasUkGovernmentWebArchive }
    optional { ?asset ex:assetHasLanguage ?language }
    optional { ?asset ex:assetHasCopyright ?copyright }
    optional { ?asset ex:assetHasAssociatedGeographicalPlace ?associatedGeographicalPlace }
    optional { ?asset ex:assetHasLegalStatus ?legalStatus }
    optional {
        ?asset ex:assetHasRetention ?retention.
        optional { ?retention ex:retentionHasFormalBody ?retentionHasFormalBody }
    }
    optional {
        ?asset ex:assetHasCreation ?creation.
        optional { ?creation ex:creationHasFormalBody ?creationHasFormalBody }
    }
    optional {
        ?asset ex:assetHasOriginDateStart ?originDateStart.
        optional { ?originDateStart ex:year ?startYear }
        optional { ?originDateStart ex:month ?startMonth }
        optional { ?originDateStart ex:day ?startDay }
    }
    optional {
        ?asset ex:assetHasOriginDateEnd ?originDateEnd.
        optional { ?originDateEnd ex:year ?endYear }
        optional { ?originDateEnd ex:month ?endMonth }
        optional { ?originDateEnd ex:day ?endDay }
    }
    optional {
        ?asset ex:assetHasOriginApproximateDateStart ?originApproximateDateStart.
        optional { ?originApproximateDateStart ex:year ?approximateStartYear }
        optional { ?originApproximateDateStart ex:month ?approximateStartMonth }
        optional { ?originApproximateDateStart ex:day ?approximateStartDay }
    }
    optional {
        ?asset ex:assetHasOriginApproximateDateEnd ?originApproximateDateEnd.
        optional { ?originApproximateDateEnd ex:year ?approximateEndYear }
        optional { ?originApproximateDateEnd ex:month ?approximateEndMonth }
        optional { ?originApproximateDateEnd ex:day ?approximateEndDay }
    }
    optional {
        ?asset ex:courtAssetHasCourtCase ?courtCase.
        optional { ?courtCase ex:courtCaseName ?courtCaseName }
        optional { ?courtCase ex:courtCaseSummaryJudgment ?courtCaseSummaryJudgment }
        optional { ?courtCase ex:courtCaseSummaryReasonsForJudgment ?courtCaseSummaryReasonsForJudgment }
        optional { ?courtCase ex:courtCaseHearingStartDate ?courtCaseHearingStartDate }
        optional { ?courtCase ex:courtCaseHearingEndDate ?courtCaseHearingEndDate }
    }
    optional {
        ?asset ex:inquiryAssetHasInquiryAppearance ?inquiryAppearance.
        optional { ?inquiryAppearance ex:inquiryWitnessName ?inquiryWitnessName }
        optional { ?inquiryAppearance ex:inquiryWitnessAppearanceDescription ?inquiryWitnessAppearanceDescription }
    }
}