prefix ex: <http://id.example.com/schema/>

construct {
    ?asset ex:assetDriId ?assetDriId;
        ex:assetReference ?reference;
        ex:assetHasSubset ?subset;
        ex:assetHasRetention ?retention;
        ex:assetHasTransfer ?assetHasTransfer;
        ex:assetHasCreation ?assetHasCreation.
    ?retention ex:importLocation ?importLocation.
    ?assetHasTransfer ex:transferHasFormalBody ?transferHasFormalBody.
    ?assetHasCreation ex:creationHasFormalBody ?creationHasFormalBody.
} where {
    bind(@id as ?assetDriId)
    ?asset ex:assetDriId ?assetDriId;
        ex:assetReference ?reference.
    optional { ?asset ex:assetHasSubset ?subset }
    optional {
        ?asset ex:assetHasRetention ?retention.
        optional { ?retention ex:importLocation ?importLocation }
    }
    optional {
        ?asset ex:assetHasTransfer ?assetHasTransfer.
        ?assetHasTransfer ex:transferHasFormalBody ?transferHasFormalBody.
    }
    optional {
        ?asset ex:assetHasCreation ?assetHasCreation.
        ?assetHasCreation ex:creationHasFormalBody ?creationHasFormalBody.
    }
}