prefix ex: <http://id.example.com/schema/>

construct {
    ?asset ex:assetDriId ?assetDriId;
        ex:assetDriXml ?assetDriXml;
        ex:assetDescription ?assetDescription;
        ex:batchDriId ?batchDriId;
        ex:consignmentTdrId ?consignmentTdrId;
        ex:assetRelationDescription ?assetRelationDescription;
        ex:assetPhysicalDescription ?assetPhysicalDescription;
        ex:assetUseRestrictionDescription ?assetUseRestrictionDescription;
        ex:evidenceProviderName ?evidenceProviderName;
        ex:investigationName ?investigationName;
        ex:courtSessionDescription ?courtSessionDescription;
        ex:courtSessionDate ?courtSessionDate;
        ex:inquirySessionDescription ?inquirySessionDescription;
        ex:inquiryHearingDate ?inquiryHearingDate;
        ex:assetHasUkGovernmentWebArchive ?assetHasUkGovernmentWebArchive;
        ex:assetHasLanguage ?language;
        ex:assetHasLegalStatus ?legalStatus;
        ex:assetHasCopyright ?copyright;
        ex:assetHasRetention ?retention;
        ex:assetHasCreation ?creation;
        ex:courtAssetHasCourtCase ?courtCase;
        ex:inquiryAssetHasInquiryAppearance ?inquiryAppearance.
    ?retention ex:retentionHasFormalBody ?retentionHasFormalBody.
    ?creation ex:creationHasFormalBody ?creationHasFormalBody.
    ?courtCase ex:courtCaseName ?courtCaseName;
        ex:courtCaseSummaryJudgment ?courtCaseSummaryJudgment;
        ex:courtCaseSummaryReasonsForJudgment ?courtCaseSummaryReasonsForJudgment;
        ex:courtCaseHearingStartDate ?courtCaseHearingStartDate;
        ex:courtCaseHearingEndDate ?courtCaseHearingEndDate.
    ?inquiryAppearance ex:inquiryWitnessName ?inquiryWitnessName;
        ex:inquiryWitnessAppearanceDescription ?inquiryWitnessAppearanceDescription.
} where {
    bind(@id as ?assetDriId)
    ?asset ex:assetDriId ?assetDriId.
    optional { ?asset ex:assetDriXml ?assetDriXml }
    optional { ?asset ex:assetDescription ?assetDescription }
    optional { ?asset ex:batchDriId ?batchDriId }
    optional { ?asset ex:consignmentTdrId ?consignmentTdrId }
    optional { ?asset ex:assetRelationDescription ?assetRelationDescription }
    optional { ?asset ex:assetPhysicalDescription ?assetPhysicalDescription }
    optional { ?asset ex:assetUseRestrictionDescription ?assetUseRestrictionDescription }
    optional { ?asset ex:evidenceProviderName ?evidenceProviderName }
    optional { ?asset ex:investigationName ?investigationName }
    optional { ?asset ex:courtSessionDescription ?courtSessionDescription }
    optional { ?asset ex:courtSessionDate ?courtSessionDate }
    optional { ?asset ex:inquirySessionDescription ?inquirySessionDescription }
    optional { ?asset ex:inquiryHearingDate ?inquiryHearingDate }
    optional { ?asset ex:assetHasUkGovernmentWebArchive ?assetHasUkGovernmentWebArchive }
    optional { ?asset ex:assetHasLanguage ?language }
    optional { ?asset ex:assetHasCopyright ?copyright }
    optional { ?asset ex:assetHasLegalStatus ?legalStatus }
    optional {
        ?asset ex:assetHasRetention ?retention.
        optional { ?retention ex:retentionHasFormalBody ?retentionHasFormalBody }
    }
    optional {
        ?asset ex:assetHasCreation ?creation.
        optional { ?creation ex:creationHasFormalBody ?creationHasFormalBody }
    }
    optional {
        ?asset ex:courtAssetHasCourtCase ?courtCase.
        optional { ?courtCase ex:courtCaseName ?courtCaseName }
        optional { ?courtCase ex:courtCaseSummaryJudgment ?courtCaseSummaryJudgment }
        optional { ?courtCase ex:courtCaseSummaryReasonsForJudgment ?courtCaseSummaryReasonsForJudgment }
        optional { ?courtCase ex:courtCaseHearingStartDate ?courtCaseHearingStartDate }
        optional { ?courtCase ex:courtCaseHearingEndDate ?courtCaseHearingEndDate }
    }
    optional {
        ?asset ex:inquiryAssetHasInquiryAppearance ?inquiryAppearance.
        optional { ?inquiryAppearance ex:inquiryWitnessName ?inquiryWitnessName }
        optional { ?inquiryAppearance ex:inquiryWitnessAppearanceDescription ?inquiryWitnessAppearanceDescription }
    }
}