prefix ex: <http://id.example.com/schema/>

construct {
    ?asset ex:assetDriId ?assetDriId;
        ex:assetName ?assetName;
        ex:assetAlternativeName ?assetAlternativeName;
        ex:assetDriXml ?assetDriXml;
        ex:assetPastReference ?assetPastReference;
        ex:assetPreviousReference ?assetPreviousReference;
        ex:assetDescription ?assetDescription;
        ex:assetSummary ?assetSummary;
        ex:batchDriId ?batchDriId;
        ex:consignmentTdrReference ?consignmentTdrReference;
        ex:fileTdrReference ?fileTdrReference;
        ex:parentTdrReference ?parentTdrReference;
        ex:assetTdrId ?assetTdrId;
        ex:assetRelationDescription ?assetRelationDescription;
        ex:assetPhysicalDescription ?assetPhysicalDescription;
        ex:assetRelationIdentifier ?assetRelationIdentifier;
        ex:assetRelationReference ?assetRelationReference;
        ex:assetUsageRestrictionDescription ?assetUsageRestrictionDescription;
        ex:assetTag ?assetTag;
        ex:assetSourceInternalName ?assetSourceInternalName;
        ex:assetConnectedAssetNote ?assetConnectedAssetNote;
        ex:assetModifiedAt ?assetModifiedAt;
        ex:assetAlternativeModifiedAt ?assetAlternativeModifiedAt;
        ex:assetAlternativeModifiedAtNote ?assetAlternativeModifiedAtNote;
        ex:filmProductionCompanyName ?filmProductionCompanyName;
        ex:filmTitle ?filmTitle;
        ex:filmDuration ?filmDuration;
        ex:photographerDescription ?photographerDescription;
        ex:courtSessionDescription ?courtSessionDescription;
        ex:courtSessionDate ?courtSessionDate;
        ex:inquirySessionDescription ?inquirySessionDescription;
        ex:inquiryHearingDate ?inquiryHearingDate;
        ex:imageSequenceStart ?imageSequenceStart;
        ex:imageSequenceEnd ?imageSequenceEnd;
        ex:paperNumber ?paperNumber;
        ex:poorLawUnionNumber ?poorLawUnionNumber;
        ex:assetHasDimension ?dimension;
        ex:sealAssetHasObverseDimension ?obverseDimension;
        ex:sealAssetHasReverseDimension ?reverseDimension;
        ex:sealOwnerName ?sealOwnerName;
        ex:sealColour ?sealColour;
        ex:emailAttachmentReference ?emailAttachmentReference;
        ex:assetHasUkGovernmentWebArchive ?assetHasUkGovernmentWebArchive;
        ex:assetHasLanguage ?language;
        ex:assetHasLegalStatus ?legalStatus;
        ex:assetHasAssetTagType ?assetHasAssetTagType;
        ex:sealAssetHasSealCategory ?sealAssetHasSealCategory;
        ex:inquiryAssetHasEvidenceProvider ?inquiryAssetHasEvidenceProvider;
        ex:inquiryAssetHasInquiryInvestigation ?inquiryAssetHasInquiryInvestigation;
        ex:assetHasCopyright ?copyright;
        ex:assetHasAssociatedGeographicalPlace ?associatedGeographicalPlace;
        ex:assetHasRetention ?retention;
        ex:assetHasCreation ?creation;
        ex:assetHasOriginDateStart ?originDateStart;
        ex:assetHasOriginDateEnd ?originDateEnd;
        ex:assetHasOriginApproximateDateStart ?originApproximateDateStart;
        ex:assetHasOriginApproximateDateEnd ?originApproximateDateEnd;
        ex:assetHasAlternativeModifiedDateStart ?modifiedDateStart;
        ex:assetHasAlternativeModifiedDateEnd ?modifiedDateEnd;
        ex:sealAssetHasStartDate ?sealDateStart;
        ex:sealAssetHasEndDate ?sealDateEnd;
        ex:sealAssetHasObverseStartDate ?sealObverseStartDate;
        ex:sealAssetHasObverseEndDate ?sealObverseEndDate;
        ex:sealAssetHasReverseStartDate ?sealReverseStartDate;
        ex:sealAssetHasReverseEndDate ?sealReverseEndDate;
        ex:courtAssetHasCourtCase ?courtCase;
        ex:inquiryAssetHasInquiryAppearance ?inquiryAppearance;
        ex:assetHasVariation ?redactedVariation, ?presentationVariation;
        ex:assetHasPerson ?person.
    ?retention ex:retentionHasFormalBody ?retentionHasFormalBody.
    ?creation ex:creationHasFormalBody ?creationHasFormalBody.
    ?originDateStart ex:dateVerbatim ?startDateVerbatim;
        ex:year ?startYear;
        ex:month ?startMonth;
        ex:day ?startDay.
    ?originDateEnd ex:dateVerbatim ?endDateVerbatim;
        ex:year ?endYear;
        ex:month ?endMonth;
        ex:day ?endDay.
    ?originApproximateDateStart ex:dateVerbatim ?approximateDateVerbatim;
        ex:year ?approximateStartYear;
        ex:month ?approximateStartMonth;
        ex:day ?approximateStartDay.
    ?originApproximateDateEnd ex:dateVerbatim ?approximateEndDateVerbatim;
        ex:year ?approximateEndYear;
        ex:month ?approximateEndMonth;
        ex:day ?approximateEndDay.
    ?modifiedDateStart ex:dateVerbatim ?modifiedStartDateVerbatim;
        ex:year ?modifiedStartYear;
        ex:month ?modifiedStartMonth;
        ex:day ?modifiedStartDay.
    ?modifiedDateEnd ex:dateVerbatim ?modifiedEndDateVerbatim;
        ex:year ?modifiedEndYear;
        ex:month ?modifiedEndMonth;
        ex:day ?modifiedEndDay.
    ?sealDateStart ex:dateVerbatim ?sealStartDateVerbatim;
        ex:year ?sealStartYear;
        ex:month ?sealStartMonth;
        ex:day ?sealStartDay.
    ?sealDateEnd ex:dateVerbatim ?sealEndDateVerbatim;
        ex:year ?sealEndYear;
        ex:month ?sealEndMonth;
        ex:day ?sealEndDay.
    ?sealObverseStartDate ex:dateVerbatim ?sealObverseStartDateVerbatim;
        ex:year ?sealObverseStartYear;
        ex:month ?sealObverseStartMonth;
        ex:day ?sealObverseStartDay.
    ?sealObverseEndDate ex:dateVerbatim ?sealObverseEndDateVerbatim;
        ex:year ?sealObverseEndYear;
        ex:month ?sealObverseEndMonth;
        ex:day ?sealObverseEndDay.
    ?sealReverseStartDate ex:dateVerbatim ?sealReverseStartDateVerbatim;
        ex:year ?sealReverseStartYear;
        ex:month ?sealReverseStartMonth;
        ex:day ?sealReverseStartDay.
    ?sealReverseEndDate ex:dateVerbatim ?sealReverseEndDateVerbatim;
        ex:year ?sealReverseEndYear;
        ex:month ?sealReverseEndMonth;
        ex:day ?sealReverseEndDay.
    ?dimension ex:firstDimensionMillimetre ?firstDimensionMillimetre;
        ex:secondDimensionMillimetre ?secondDimensionMillimetre.
    ?obverseDimension ex:firstDimensionMillimetre ?obverseFirstDimensionMillimetre;
        ex:secondDimensionMillimetre ?obverseSecondDimensionMillimetre.
    ?reverseDimension ex:firstDimensionMillimetre ?reverseFirstDimensionMillimetre;
        ex:secondDimensionMillimetre ?reverseSecondDimensionMillimetre.
    ?courtCase ex:courtCaseSequence ?courtCaseSequence;
        ex:courtCaseReference ?courtCaseReference;
        ex:courtCaseName ?courtCaseName;
        ex:courtCaseSummary ?courtCaseSummary;
        ex:courtCaseSummaryJudgment ?courtCaseSummaryJudgment;
        ex:courtCaseSummaryReasonsForJudgment ?courtCaseSummaryReasonsForJudgment;
        ex:courtCaseHearingStartDate ?courtCaseHearingStartDate;
        ex:courtCaseHearingEndDate ?courtCaseHearingEndDate.
    ?inquiryAppearance ex:inquiryAppearanceSequence ?inquiryAppearanceSequence;
        ex:inquiryAppearanceHasInquiryWitness ?inquiryAppearanceHasInquiryWitness;
        ex:inquiryWitnessAppearanceDescription ?inquiryWitnessAppearanceDescription.
    ?redactedVariation ex:redactedVariationSequence ?redactedVariationSequence.
    ?presentationVariation ex:presentationVariationSequence ?presentationVariationSequence.
    ?person ex:personFamilyName ?personFamilyName;
        ex:personGivenName ?personGivenName;
        ex:seamanServiceNumber ?seamanServiceNumber;
        ex:personHasDateOfBirth ?dateOfBirth;
        ex:personHasBirthAddress ?personHasBirthAddress.
    ?dateOfBirth ex:dateVerbatim ?dateOfBirthDateVerbatim;
        ex:year ?dateOfBirthYear;
        ex:month ?dateOfBirthMonth;
        ex:day ?dateOfBirthDay.
} where {
    bind(@id as ?assetDriId)
    ?asset ex:assetDriId ?assetDriId.
    optional { ?asset ex:assetDriXml ?assetDriXml }
    optional { ?asset ex:assetName ?assetName }
    optional { ?asset ex:assetAlternativeName ?assetAlternativeName }
    optional { ?asset ex:assetPastReference ?assetPastReference }
    optional { ?asset ex:assetPreviousReference ?assetPreviousReference }
    optional { ?asset ex:assetDescription ?assetDescription }
    optional { ?asset ex:assetSummary ?assetSummary }
    optional { ?asset ex:batchDriId ?batchDriId }
    optional { ?asset ex:consignmentTdrReference ?consignmentTdrReference }
    optional { ?asset ex:fileTdrReference ?fileTdrReference }
    optional { ?asset ex:parentTdrReference ?parentTdrReference }
    optional { ?asset ex:assetTdrId ?assetTdrId }
    optional { ?asset ex:assetRelationDescription ?assetRelationDescription }
    optional { ?asset ex:assetPhysicalDescription ?assetPhysicalDescription }
    optional { ?asset ex:assetRelationIdentifier ?assetRelationIdentifier }
    optional { ?asset ex:assetRelationReference ?assetRelationReference }
    optional { ?asset ex:assetUsageRestrictionDescription ?assetUsageRestrictionDescription }
    optional { ?asset ex:assetTag ?assetTag }
    optional { ?asset ex:assetSourceInternalName ?assetSourceInternalName }
    optional { ?asset ex:assetConnectedAssetNote ?assetConnectedAssetNote }
    optional { ?asset ex:assetModifiedAt ?assetModifiedAt }
    optional { ?asset ex:assetAlternativeModifiedAt ?assetAlternativeModifiedAt }
    optional { ?asset ex:assetAlternativeModifiedAtNote ?assetAlternativeModifiedAtNote }
    optional { ?asset ex:filmProductionCompanyName ?filmProductionCompanyName }
    optional { ?asset ex:filmTitle ?filmTitle }
    optional { ?asset ex:filmDuration ?filmDuration }
    optional { ?asset ex:photographerDescription ?photographerDescription }
    optional { ?asset ex:courtSessionDescription ?courtSessionDescription }
    optional { ?asset ex:courtSessionDate ?courtSessionDate }
    optional { ?asset ex:inquirySessionDescription ?inquirySessionDescription }
    optional { ?asset ex:inquiryHearingDate ?inquiryHearingDate }
    optional { ?asset ex:imageSequenceStart ?imageSequenceStart }
    optional { ?asset ex:imageSequenceEnd ?imageSequenceEnd }
    optional { ?asset ex:paperNumber ?paperNumber }
    optional { ?asset ex:poorLawUnionNumber ?poorLawUnionNumber }
    optional { ?asset ex:sealOwnerName ?sealOwnerName }
    optional { ?asset ex:sealColour ?sealColour }
    optional { ?asset ex:emailAttachmentReference ?emailAttachmentReference }
    optional { ?asset ex:assetHasUkGovernmentWebArchive ?assetHasUkGovernmentWebArchive }
    optional { ?asset ex:assetHasLanguage ?language }
    optional { ?asset ex:assetHasCopyright ?copyright }
    optional { ?asset ex:assetHasAssociatedGeographicalPlace ?associatedGeographicalPlace }
    optional { ?asset ex:assetHasLegalStatus ?legalStatus }
    optional { ?asset ex:assetHasAssetTagType ?assetHasAssetTagType }
    optional { ?asset ex:sealAssetHasSealCategory ?sealAssetHasSealCategory }
    optional { ?asset ex:inquiryAssetHasEvidenceProvider ?inquiryAssetHasEvidenceProvider }
    optional { ?asset ex:inquiryAssetHasInquiryInvestigation ?inquiryAssetHasInquiryInvestigation }
    optional {
        ?asset ex:assetHasDimension ?dimension.
        optional { ?dimension ex:firstDimensionMillimetre ?firstDimensionMillimetre }
        optional { ?dimension ex:secondDimensionMillimetre ?secondDimensionMillimetre }
    }
    optional {
        ?asset ex:sealAssetHasObverseDimension ?obverseDimension.
        optional { ?obverseDimension ex:firstDimensionMillimetre ?obverseFirstDimensionMillimetre }
        optional { ?obverseDimension ex:secondDimensionMillimetre ?obverseSecondDimensionMillimetre }
    }
    optional {
        ?asset ex:sealAssetHasReverseDimension ?reverseDimension.
        optional { ?reverseDimension ex:firstDimensionMillimetre ?reverseFirstDimensionMillimetre }
        optional { ?reverseDimension ex:secondDimensionMillimetre ?reverseSecondDimensionMillimetre }
    }
    optional {
        ?asset ex:assetHasRetention ?retention.
        optional { ?retention ex:retentionHasFormalBody ?retentionHasFormalBody }
    }
    optional {
        ?asset ex:assetHasCreation ?creation.
        optional { ?creation ex:creationHasFormalBody ?creationHasFormalBody }
    }
    optional {
        ?asset ex:assetHasOriginDateStart ?originDateStart.
        optional { ?originDateStart ex:dateVerbatim ?startDateVerbatim }
        optional { ?originDateStart ex:year ?startYear }
        optional { ?originDateStart ex:month ?startMonth }
        optional { ?originDateStart ex:day ?startDay }
    }
    optional {
        ?asset ex:assetHasOriginDateEnd ?originDateEnd.
        optional { ?originDateEnd ex:dateVerbatim ?endDateVerbatim }
        optional { ?originDateEnd ex:year ?endYear }
        optional { ?originDateEnd ex:month ?endMonth }
        optional { ?originDateEnd ex:day ?endDay }
    }
    optional {
        ?asset ex:assetHasOriginApproximateDateStart ?originApproximateDateStart.
        optional { ?originApproximateDateStart ex:dateVerbatim ?approximateDateVerbatim }
        optional { ?originApproximateDateStart ex:year ?approximateStartYear }
        optional { ?originApproximateDateStart ex:month ?approximateStartMonth }
        optional { ?originApproximateDateStart ex:day ?approximateStartDay }
    }
    optional {
        ?asset ex:assetHasOriginApproximateDateEnd ?originApproximateDateEnd.
        optional { ?originApproximateDateEnd ex:dateVerbatim ?approximateEndDateVerbatim }
        optional { ?originApproximateDateEnd ex:year ?approximateEndYear }
        optional { ?originApproximateDateEnd ex:month ?approximateEndMonth }
        optional { ?originApproximateDateEnd ex:day ?approximateEndDay }
    }
    optional {
        ?asset ex:assetHasAlternativeModifiedDateStart ?modifiedDateStart.
        optional { ?modifiedDateStart ex:dateVerbatim ?modifiedStartDateVerbatim }
        optional { ?modifiedDateStart ex:year ?modifiedStartYear }
        optional { ?modifiedDateStart ex:month ?modifiedStartMonth }
        optional { ?modifiedDateStart ex:day ?modifiedStartDay }
    }
    optional {
        ?asset ex:assetHasAlternativeModifiedDateEnd ?modifiedDateEnd.
        optional { ?modifiedDateEnd ex:dateVerbatim ?modifiedEndDateVerbatim }
        optional { ?modifiedDateEnd ex:year ?modifiedEndYear }
        optional { ?modifiedDateEnd ex:month ?modifiedEndMonth }
        optional { ?modifiedDateEnd ex:day ?modifiedEndDay }
    }
    optional {
        ?asset ex:sealAssetHasStartDate ?sealDateStart.
        optional { ?sealDateStart ex:dateVerbatim ?sealStartDateVerbatim }
        optional { ?sealDateStart ex:year ?sealStartYear }
        optional { ?sealDateStart ex:month ?sealStartMonth }
        optional { ?sealDateStart ex:day ?sealStartDay }
    }
    optional {
        ?asset ex:sealAssetHasEndDate ?sealDateEnd.
        optional { ?sealDateEnd ex:dateVerbatim ?sealEndDateVerbatim }
        optional { ?sealDateEnd ex:year ?sealEndYear }
        optional { ?sealDateEnd ex:month ?sealEndMonth }
        optional { ?sealDateEnd ex:day ?sealEndDay }
    }
    optional {
        ?asset ex:sealAssetHasObverseStartDate ?sealObverseStartDate.
        optional { ?sealObverseStartDate ex:dateVerbatim ?sealObverseStartDateVerbatim }
        optional { ?sealObverseStartDate ex:year ?sealObverseStartYear }
        optional { ?sealObverseStartDate ex:month ?sealObverseStartMonth }
        optional { ?sealObverseStartDate ex:day ?sealObverseStartDay }
    }
    optional {
        ?asset ex:sealAssetHasObverseEndDate ?sealObverseEndDate.
        optional { ?sealObverseEndDate ex:dateVerbatim ?sealObverseEndDateVerbatim }
        optional { ?sealObverseEndDate ex:year ?sealObverseEndYear }
        optional { ?sealObverseEndDate ex:month ?sealObverseEndMonth }
        optional { ?sealObverseEndDate ex:day ?sealObverseEndDay }
    }
    optional {
        ?asset ex:sealAssetHasReverseStartDate ?sealReverseStartDate.
        optional { ?sealReverseStartDate ex:year ?sealReverseStartYear }
        optional { ?sealReverseStartDate ex:month ?sealReverseStartMonth }
        optional { ?sealReverseStartDate ex:day ?sealReverseStartDay }
    }
    optional {
        ?asset ex:sealAssetHasReverseEndDate ?sealReverseEndDate.
        optional { ?sealReverseEndDate ex:dateVerbatim ?sealReverseEndDateVerbatim }
        optional { ?sealReverseEndDate ex:year ?sealReverseEndYear }
        optional { ?sealReverseEndDate ex:month ?sealReverseEndMonth }
        optional { ?sealReverseEndDate ex:day ?sealReverseEndDay }
    }
    optional {
        ?asset ex:courtAssetHasCourtCase ?courtCase.
        optional { ?courtCase ex:courtCaseSequence ?courtCaseSequence }
        optional { ?courtCase ex:courtCaseReference ?courtCaseReference }
        optional { ?courtCase ex:courtCaseName ?courtCaseName }
        optional { ?courtCase ex:courtCaseSummary ?courtCaseSummary }
        optional { ?courtCase ex:courtCaseSummaryJudgment ?courtCaseSummaryJudgment }
        optional { ?courtCase ex:courtCaseSummaryReasonsForJudgment ?courtCaseSummaryReasonsForJudgment }
        optional { ?courtCase ex:courtCaseHearingStartDate ?courtCaseHearingStartDate }
        optional { ?courtCase ex:courtCaseHearingEndDate ?courtCaseHearingEndDate }
    }
    optional {
        ?asset ex:inquiryAssetHasInquiryAppearance ?inquiryAppearance.
        optional { ?inquiryAppearance ex:inquiryAppearanceSequence ?inquiryAppearanceSequence }
        optional { ?inquiryAppearance ex:inquiryAppearanceHasInquiryWitness ?inquiryAppearanceHasInquiryWitness }
        optional { ?inquiryAppearance ex:inquiryWitnessAppearanceDescription ?inquiryWitnessAppearanceDescription }
    }
    optional {
        ?asset ex:assetHasVariation ?redactedVariation.
        ?redactedVariation ex:redactedVariationSequence ?redactedVariationSequence.
    }
    optional {
        ?asset ex:assetHasVariation ?presentationVariation.
        ?presentationVariation ex:presentationVariationSequence ?presentationVariationSequence.
    }
    optional {
        ?asset ex:assetHasPerson ?person.
        optional { ?person ex:personFamilyName ?personFamilyName }
        optional { ?person ex:personGivenName ?personGivenName }
        optional { ?person ex:seamanServiceNumber ?seamanServiceNumber }
        optional {
            ?person ex:personHasDateOfBirth ?dateOfBirth.
            optional { ?dateOfBirth ex:dateVerbatim ?dateOfBirthDateVerbatim }
            optional { ?dateOfBirth ex:year ?dateOfBirthYear }
            optional { ?dateOfBirth ex:month ?dateOfBirthMonth }
            optional { ?dateOfBirth ex:day ?dateOfBirthDay }
        }
        optional { ?person ex:personHasBirthAddress ?personHasBirthAddress }
    }
}