prefix ex: <http://id.example.com/schema/>
            
construct {
    ?s ex:assetReference ?assetReference.
} where {
    bind(@id as ?id)
    {
        ?s ex:assetReference ?id;
        	ex:assetReference ?assetReference.
    }
    union
    {
        ?s ex:assetDriId ?id;
        	ex:assetReference ?assetReference.
    }
}