prefix ex: <http://id.example.com/schema/>

construct {
    ?s ex:courtCaseReference ?id0
} where {
    bind(@id0 as ?id0)
    bind(@id1 as ?id1)
    ?s ex:courtCaseReference ?id0;
        ex:courtCaseHasCourtAsset/ex:assetReference ?id1.
}