prefix ex: <http://id.example.com/schema/>
            
construct {
    ?s ex:geographicalPlaceName ?geographicalPlaceName.
} where {
    bind(@id as ?geographicalPlaceName)
    ?s ex:geographicalPlaceName ?geographicalPlaceName.
}