prefix ex: <http://id.example.com/schema/>

construct {
    ?s ex:inquiryInvestigationName ?inquiryInvestigationName.
} where {
    bind(@id as ?inquiryInvestigationName)
    ?s ex:inquiryInvestigationName ?inquiryInvestigationName.
}