prefix ex: <http://id.example.com/schema/>
            
construct {
    ?s ex:legislationHasUkLegislation ?legislationHasUkLegislation.
} where {
    ?s ex:legislationHasUkLegislation ?legislationHasUkLegislation.
}