prefix ex: <http://id.example.com/schema/>

construct {
    ?variation ex:variationDriId ?variationDriId;
        ex:variationDriXml ?variationDriXml;
        ex:variationPastName ?variationPastName;
        ex:variationNote ?variationNote;
        ex:variationRelativeLocation ?variationRelativeLocation;
        ex:variationPhysicalConditionDescription ?variationPhysicalConditionDescription;
        ex:variationReferenceGoogleId ?variationReferenceGoogleId;
        ex:variationReferenceParentGoogleId ?variationReferenceParentGoogleId;
        ex:scannerOperatorIdentifier ?scannerOperatorIdentifier;
        ex:scannerIdentifier ?scannerIdentifier;
        ex:scannedVariationHasScannerGeographicalPlace ?scannedVariationHasScannerGeographicalPlace;
        ex:scannedVariationHasImageSplit ?scannedVariationHasImageSplit;
        ex:scannedVariationHasImageCrop ?scannedVariationHasImageCrop;
        ex:scannedVariationHasImageDeskew ?scannedVariationHasImageDeskew;
        <http://purl.org/dc/terms/description> ?dctermsDescription;
        ex:variationHasDatedNote ?datedNote.
    ?datedNote ex:archivistNote ?archivistNote;
        ex:datedNoteHasDate ?date.
    ?date ex:year ?year;
          ex:month ?month;
          ex:day ?day.
} where {
    bind(@id as ?variationDriId)
    ?variation ex:variationDriId ?variationDriId.
    optional { ?variation ex:variationDriXml ?variationDriXml }
    optional { ?variation ex:variationPastName ?variationPastName }
    optional { ?variation ex:variationNote ?variationNote }
    optional { ?variation ex:variationRelativeLocation ?variationRelativeLocation }
    optional { ?variation ex:variationPhysicalConditionDescription ?variationPhysicalConditionDescription }
    optional { ?variation ex:variationReferenceGoogleId ?variationReferenceGoogleId }
    optional { ?variation ex:variationReferenceParentGoogleId ?variationReferenceParentGoogleId }
    optional { ?variation ex:scannerOperatorIdentifier ?scannerOperatorIdentifier }
    optional { ?variation ex:scannerIdentifier ?scannerIdentifier }
    optional { ?variation ex:scannedVariationHasScannerGeographicalPlace ?scannedVariationHasScannerGeographicalPlace }
    optional { ?variation ex:scannedVariationHasImageSplit ?scannedVariationHasImageSplit }
    optional { ?variation ex:scannedVariationHasImageCrop ?scannedVariationHasImageCrop }
    optional { ?variation ex:scannedVariationHasImageDeskew ?scannedVariationHasImageDeskew }
    optional { ?variation <http://purl.org/dc/terms/description> ?dctermsDescription }
    optional {
        ?variation ex:variationHasDatedNote ?datedNote.
        optional { ?datedNote ex:archivistNote ?archivistNote }
        optional {
            ?datedNote ex:datedNoteHasDate ?date.
            optional { ?date ex:year ?year }
            optional { ?date ex:month ?month }
            optional { ?date ex:day ?day }
        }
    }
}