prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix dri: <http://nationalarchives.gov.uk/terms/dri#> 

select ?label ?comment where {
    ?c a dri:RetentionJustificationType;
        rdfs:comment ?comment;
    	rdfs:label ?label.
}