prefix ex: <http://id.example.com/schema/>

construct {
    ?asset ex:assetReference ?assetReference;
        ex:assetDriXml ?assetDriXml;
        ex:wo409SubsetDriXml ?wo409SubsetDriXml;
        ex:assetHasVariation ?variation.
    ?variation ex:redactedVariationSequence ?redactedVariationSequence;
        ex:variationSequence ?variationSequence;
        ex:variationDriId ?variationDriId;
        ex:variationDriXml ?variationDriXml.
} where {
    bind(@id as ?asset)
    ?asset ex:assetReference ?assetReference.
    optional { ?asset ex:assetDriXml ?assetDriXml }
    optional { ?asset ex:wo409SubsetDriXml ?wo409SubsetDriXml }
    optional {
        ?asset ex:assetHasVariation ?variation.
        optional { ?variation ex:redactedVariationSequence ?redactedVariationSequence }
        optional { ?variation ex:variationSequence ?variationSequence }
        optional { ?variation ex:variationDriId ?variationDriId }
        optional { ?variation ex:variationDriXml ?variationDriXml }
    }
}