prefix ex: <http://id.example.com/schema/>

select ?assetDriId ?reference ?redactedVariationSequence
    ?variationName
	?retentionBodyName ?isPublicDescription ?isPublicName
    ?missingSensitiveName ?missingSensitiveDescription
    ?startCoveringDate ?endCoveringDate ?accessConditionCode ?closureStatus
    ?sensitivityReviewRestrictionCalculationStartDate
    ?sensitivityReviewRestrictionDuration
	?sensitivityReviewRestrictionEndYear
where {
    ?asset ex:assetDriId ?assetDriId;
        ex:assetReference ?reference;
        ex:assetHasVariation ?variation.
    {
        select ?asset where {
            bind(@id as ?id)
            ?asset ex:assetHasSubset/ex:subsetHasBroaderSubset*/ex:subsetReference ?id.
        }
        order by ?asset
        limit @limit offset @offset
    }
    optional { ?asset ex:assetName ?assetName }
    optional {
        ?asset ex:assetHasRetention ?assetHasRetention.
        ?assetHasRetention ex:retentionHasFormalBody ?retentionHasFormalBody.
        ?retentionHasFormalBody ex:formalBodyName ?retentionBodyName.
    }
    optional {
        ?asset ex:assetHasSensitivityReview ?srA.
        filter not exists { ?futureSrA ex:sensitivityReviewHasPastSensitivityReview ?srA }
        optional {
            ?srA ex:sensitivityReviewSensitiveDescription ?sensitivityReviewSensitiveDescriptionA.
        }
        optional {
            ?srA ex:sensitivityReviewSensitiveName ?sensitivityReviewSensitiveNameA.
        }
    }
    optional { ?asset ex:inquiryHearingDate ?inquiryHearingDate }
    optional {
        ?asset ex:assetHasOriginDateStart|ex:assetHasOriginApproximateDateStart ?assetHasOriginDateStart.
        ?assetHasOriginDateStart ex:year ?startYear.
        optional { ?assetHasOriginDateStart ex:month ?startMonth }
        optional { ?assetHasOriginDateStart ex:day ?startDay }
        bind(concat(str(?startYear), coalesce(str(?startMonth), '--01'), coalesce(str(?startDay), '---01')) as ?startOriginDate)
    }
    optional {
        ?asset ex:assetHasOriginDateEnd|ex:assetHasOriginApproximateDateEnd ?assetHasOriginDateEnd.
        ?assetHasOriginDateEnd ex:year ?endYear.
        optional { ?assetHasOriginDateEnd ex:month ?endMonth }
        optional { ?assetHasOriginDateEnd ex:day ?endDay }
        bind(concat(str(?endYear), coalesce(str(?endMonth), '--12'), coalesce(str(?endDay), '')) as ?endOriginDate)
    }
    optional { ?asset ex:assetModifiedAt ?assetModifiedAt }
    optional { ?asset ex:assetAlternativeModifiedAt ?assetAlternativeModifiedAt }
    optional {
        ?asset ex:assetHasAlternativeModifiedDateStart ?modifiedDateStart.
        ?modifiedDateStart ex:year ?modifiedStartYear.
        optional { ?modifiedDateStart ex:month ?modifiedStartMonth }
        optional { ?modifiedDateStart ex:day ?modifiedStartDay }
        bind(concat(str(?modifiedStartYear), coalesce(str(?modifiedStartMonth), '--01'), coalesce(str(?modifiedStartDay), '---01')) as ?startModifiedDate)
    }
    optional {
        ?asset ex:assetHasAlternativeModifiedDateEnd ?modifiedDateEnd.
        ?modifiedDateEnd ex:year ?modifiedEndYear.
        optional { ?modifiedDateEnd ex:month ?modifiedEndMonth }
        optional { ?modifiedDateEnd ex:day ?modifiedEndDay }
        bind(concat(str(?modifiedEndYear), coalesce(str(?modifiedEndMonth), '--12'), coalesce(str(?modifiedEndDay), '')) as ?endModifiedDate)
    }
    bind(coalesce(str(?inquiryHearingDate), str(?assetAlternativeModifiedAt), ?startModifiedDate, ?startOriginDate, str(?assetModifiedAt)) as ?startCoveringDate)
    bind(coalesce(str(?inquiryHearingDate), str(?assetAlternativeModifiedAt), ?endModifiedDate, ?endOriginDate, str(?assetModifiedAt)) as ?endCoveringDate)
    optional { ?variation ex:redactedVariationSequence ?redactedVariationSequence }
    optional {
        ?variation ex:variationHasSensitivityReview ?sr.
        filter not exists { ?futureSr ex:sensitivityReviewHasPastSensitivityReview ?sr }
        optional { 
            ?sr ex:sensitivityReviewHasAccessCondition ?ac.
            ?ac ex:accessConditionCode ?accessConditionCode.
            bind(?accessConditionCode as ?closureStatus)
        }
        optional { ?sr ex:sensitivityReviewDate ?sensitivityReviewDate }
        optional {
            ?sr ex:sensitivityReviewSensitiveDescription ?sensitivityReviewSensitiveDescriptionV.
        }
        optional {
            ?sr ex:sensitivityReviewSensitiveName ?sensitivityReviewSensitiveNameV.
        }
        optional {
            ?sr ex:sensitivityReviewHasSensitivityReviewRestriction ?restriction.
            optional { ?restriction ex:sensitivityReviewRestrictionCalculationStartDate ?sensitivityReviewRestrictionCalculationStartDate }
            optional { ?restriction ex:sensitivityReviewRestrictionDuration ?sensitivityReviewRestrictionDuration }
            optional { ?restriction ex:sensitivityReviewRestrictionEndYear ?sensitivityReviewRestrictionEndYear }
        }
        optional { 
            ?sr ex:sensitivityReviewHasMissingSensitiveInformation ?sensitivityReviewHasMissingSensitiveInformation
        }
    }
    bind(coalesce(?sensitivityReviewSensitiveDescriptionV, ?sensitivityReviewSensitiveDescriptionA) as ?isPublicDescription)
    bind(coalesce(?sensitivityReviewSensitiveNameV, ?sensitivityReviewSensitiveNameA) as ?isPublicName)
    bind(coalesce(?sensitivityReviewSensitiveNameV, ?sensitivityReviewSensitiveNameA, ?assetName) as ?variationName)
    bind(if(?sensitivityReviewHasMissingSensitiveInformation = ex:MissingSensitiveName, "true"^^xsd:boolean, "false"^^xsd:boolean) as ?missingSensitiveName)
    bind(if(?sensitivityReviewHasMissingSensitiveInformation = ex:MissingSensitiveDescription, "true"^^xsd:boolean, "false"^^xsd:boolean) as ?missingSensitiveDescription)
}
