prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix dri: <http://nationalarchives.gov.uk/terms/dri#>

select ?s ?label where {
    bind(@id as ?s)
    ?s a dri:ClosureType;
    	rdfs:label ?label.
}