prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix dri: <http://nationalarchives.gov.uk/terms/dri#> 
prefix dcterms: <http://purl.org/dc/terms/>
prefix ex: <http://id.example.com/schema/>

construct {
    ?d ex:variationDriId ?d;
        ex:variationHasAsset [
	 	    ex:assetReference ?assetReference
    	];
    	ex:variationName ?label.
} where {
    bind(@id as ?d)
    ?d rdfs:label ?label;
        ^dri:file/dri:parent/rdfs:label ?assetReference.
}