prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix dri: <http://nationalarchives.gov.uk/terms/dri#> 
prefix dcterms: <http://purl.org/dc/terms/>
prefix ex: <http://id.example.com/schema/>

select distinct ?s where {
    bind(@id as ?code)
    bind(replace(@id,' ','_') as ?code2)
    ?s rdfs:label ?reference.
    {
        ?s a dri:DeliverableUnit;
    	    dri:isPartOfSeries/rdfs:label ?code.
    }
    union
    {
        ?s a dri:DeliverableUnit;
    	    dri:isPartOfSeries/rdfs:label ?code2.
    }
    ?m dri:file ?f;
        dri:parent ?s.
}
order by ?s
