select p.CATALOGUEREFERENCE, a.CATALOGUEREFERENCE as asset, x.XMLCLOB from XMLMETADATA x
join DELIVERABLEUNIT p on p.METADATAREF = x.METADATAREF
join DELIVERABLEUNIT a on a.DELIVERABLEUNITREF = p.PARENTREF
join DELIVERABLEUNIT du on du.DELIVERABLEUNITREF = p.TOPLEVELREF
left join DELIVERABLEUNIT u on u.PARENTREF = p.DELIVERABLEUNITREF
where $code = 'ADM 158' and du.CATALOGUEREFERENCE = 'ADM/158' and u.DELIVERABLEUNITREF is null
order by p.rowid
limit $limit offset $offset
