select p.CATALOGUEREFERENCE, x.XMLCLOB from XMLMETADATA x 
join DELIVERABLEUNIT p on p.METADATAREF = x.METADATAREF
left join DELIVERABLEUNIT u on u.PARENTREF = p.DELIVERABLEUNITREF
join DELIVERABLEUNIT du on du.DELIVERABLEUNITREF = p.TOPLEVELREF
where $code = 'ADM 158' and du.CATALOGUEREFERENCE = 'ADM/158' and u.DELIVERABLEUNITREF is null
order by p.rowid
limit $limit offset $offset