name: Ontology tests

on:
  push:
    paths:
      - 'Ontology.ttl'
      - '**/OntologyTest.cs'
  pull_request:
    paths:
      - 'Ontology.ttl'
      - '**/OntologyTest.cs'

jobs:
  test:
    name: Testing Ontology file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: |
            cd Tests
            dotnet run --no-restore --project "Ontology.Tests" --configuration Release