name: Publish

on: workflow_dispatch

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup .NET
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
        with:
          dotnet-version: 10

      - name: Install dependencies
        run: dotnet restore
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1

      - name: Publish
        run: dotnet publish Migration --runtime win-x64 --framework net10.0 --configuration Release --self-contained true --output "publish/win-x64/" /p:DebugType=embedded /p:DebugSymbols=false /p:PublishSingleFile=true
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1

      - name: Upload
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: migration-win-x64
          path: publish/win-x64/
          if-no-files-found: error
